# Generated by Django 5.0.1 on 2024-02-16 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mep',
            fields=[
                ('mep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('eu_group_short', models.CharField(max_length=200)),
                ('eu_group_long', models.CharField(max_length=200)),
                ('national_party', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('twitter', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('website', models.URLField(null=True)),
                ('eu_page_url', models.URLField(null=True)),
                ('photo_url', models.URLField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance', models.CharField(max_length=3, null=True)),
                ('comment', models.TextField(blank=True)),
                ('mep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yvm.mep')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_number', models.PositiveSmallIntegerField(default=0)),
                ('vote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vote_date', models.DateField()),
                ('xml_url', models.URLField()),
                ('title', models.CharField(max_length=1000)),
                ('text_id', models.CharField(max_length=200)),
                ('epref', models.CharField(max_length=200)),
                ('total_for', models.IntegerField()),
                ('total_against', models.IntegerField()),
                ('total_abs', models.IntegerField()),
                ('short_desc', models.CharField(max_length=1000, null=True)),
                ('summary_url', models.URLField()),
                ('procedure_url', models.URLField(default=None, null=True)),
                ('debate_url', models.URLField(default=None, null=True)),
                ('topic', models.CharField(max_length=100)),
                ('meps', models.ManyToManyField(through='yvm.Position', to='yvm.mep')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yvm.vote'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('mep', 'vote'), name='unique_position'),
        ),
    ]
